# Generated by Django 3.2.22 on 2023-10-13 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_de_tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Observaciones', models.TextField(max_length=2500)),
                ('Fecha_de_Asignación', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripción', models.TextField(max_length=2500)),
                ('Duración_Estimada', models.FloatField()),
                ('Fecha_de_Inicio', models.DateField(default=django.utils.timezone.now)),
                ('Fecha_de_Finalización', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo_electronico', models.CharField(max_length=100, unique=True)),
                ('Contraseña', models.CharField(max_length=20)),
                ('Fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(max_length=100)),
                ('Descripción', models.TextField()),
                ('Prioridad', models.IntegerField()),
                ('Estadio', models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'Progreso'), ('Co', 'Completada')], max_length=2)),
                ('Completada', models.BooleanField()),
                ('Fecha_de_Creación', models.DateField(default=django.utils.timezone.now)),
                ('Hora_de_Vencimiento', models.TimeField(default=django.utils.timezone.now)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.proyecto')),
                ('usuario_asignado', models.ManyToManyField(related_name='encargados', through='modelo.Asignacion_de_tarea', to='modelo.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(related_name='colaborador', to='modelo.Usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='modelo.usuario'),
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=30, unique=True)),
                ('tarea', models.ManyToManyField(to='modelo.Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.TextField(max_length=2500)),
                ('Fecha_de_Comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.usuario')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion_de_tarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.tarea'),
        ),
        migrations.AddField(
            model_name='asignacion_de_tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.usuario'),
        ),
    ]
